name: Deploy to VPS

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Start SSH Agent and add key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -

    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd /test-action
          git pull origin master
        EOF
